// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNumbers(arg1, arg2) {
  return window['go']['app']['App']['AddNumbers'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function SelectFile() {
  return window['go']['app']['App']['SelectFile']();
}
